site_name: My Docs
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
plugins:
- search
repo_url: https://github.com/feven-redhat/minilab
repo_name: feven-redhat/minilab
docs_dir: content
markdown_extensions:
- toc:
    toc_depth: "2-3"
nav:
- Home: index.md
- 'Minilab guides':
  - openshift/index.md
  - openshift/01_introduction.md
  - openshift/02_rhel-installation.md
  - openshift/03_microshift-installation.md
  - openshift/04_microshift-connection.md
  - openshift/05_add-console.md
